version: '3.8'

services:
  node-app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/nextjs-app
    restart: always
    command: npm run dev
